# Generated by Django 4.1.3 on 2022-11-04 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("snippets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("TEXT", models.TextField(blank=True, verbose_name="コメント")),
                (
                    "commented_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="投稿日"),
                ),
                (
                    "commented_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="コメンテーター",
                    ),
                ),
                (
                    "commented_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="snippets.snippet",
                        verbose_name="投稿先",
                    ),
                ),
            ],
        ),
    ]
